### ISSUE TITLE
Production jobs failing with TypeError

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#24]
## Describe the bug
We've configured a production project that is the _exact_ copy of staging (same jobs, adaptor version, etc.). However, tests on prod fail when we try to upsert cases in Primero - see failure: https://www.openfn.org/projects/pderjw/runs/0615beb2-df29-7efd-a1ed-18ca70444493

Tests on staging succeed - see successful run: https://www.openfn.org/projects/p5kaap/runs/06151868-fd08-7b57-bafa-cff627b1c182

The only difference between the 2 project configurations are the credentials of the target systems (different instances). 

## To Reproduce
See run failure on prod for job 2: https://www.openfn.org/projects/pderjw/runs/0615beb2-df29-7efd-a1ed-18ca70444493
Feel free to test on prod while re-running job 1: https://www.openfn.org/projects/pderjw/runs/0615beb2-6a4d-79ff-8cdc-01a918ff65f2

### expression.js
https://www.openfn.org/projects/pderjw/jobs/jyx54a

### state.json
HIS (job 1) - See `MOPH Thailand HIS API - PROD`
Re-run this job to generate state for the Job 2...

Primero (job 2) - See `Primero Thailand API User (PROD)`

**Comment by taylordowns2000** [comment]
@ritazagoni , @aleksa-krolls , please upgrade to `v2.3.2` so you can reliably see the certificate error we're getting on the prod server.

**Comment by aleksa-krolls** [comment]
Thanks @taylordowns2000 ... seeing the certificate error on prod: https://www.openfn.org/projects/pderjw/runs/0615c001-9c23-7197-a2c0-260e3a227c1e
