### ISSUE TITLE
Load testing: Scripts to generate batches of Messages to post to OpenFn Inbox

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#25]
## Background, context, and business value
In preparation for go-live across multiple hospitals in Thailand at the end of the month, the UNICEF team wants to conduct performance testing on the OpenFn integration solution to test (1) OpenFn load performance, as well as (2) performance of target system APIs when multiple requests are sent at the same time. 

Project will be live in 5 hospitals in the pilot, but will scale nationally... so we want to try to simulate a scenario where there is a high volume of user activity and requests to sync Primero with the HIS API. (Causing a volume of notifications to be sent to the OpenFn inbox, triggering several API requests to HIS and then the Primero API.)

How the sync works: 
1. Primero end-user clicks "Sync" button to request that the case be updated with health history info from HIS. On click, the Primero webhook automatically sends notification to OpenFn --> see example state: https://github.com/OpenFn/primero-thailand/blob/master/sampleData/sampleSyncRequestFromPrimero.json
2. This triggers job 1 to get info from HIS, using `national_id_no` to filter for a specific patient: https://www.openfn.org/projects/p5kaap/jobs/jv7r65
3. When HIS responds, job 2 is triggered to update Primero cases with info from response, using `record_id` to upsert cases: https://www.openfn.org/projects/p5kaap/jobs/jyzqmq

See project docs here: https://github.com/OpenFn/primero-thailand/blob/master/README.md

## The specific request, in as few words as possible
For load testing, we want to simulate step 1 above and send several ["sync" notifications](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/sampleSyncRequestFromPrimero.json) to the OpenFn Inbox in batches of 20 requests, and then 50, and then 100/200/400, etc. 

For each batch, these notifications should be posted to the [OpenFn Inbox]() _at the same time_  (or milliseconds apart) to simulate a scenario where dozens of case workers are requesting case syncs in the same time window. 

Let's set this up in staging (and later this week we'll run in the OpenFn prod inbox). 

## state.json
For creating notifications to send to the OpenFn inbox...
[See this sheet - Column C](https://docs.google.com/spreadsheets/d/1hud1zJMunfK2zwIBiMruiAr4YtvDBsGLz_YaTXSSSiM/edit#gid=1819608640) for 20 sample notifications we can post to the Inbox. 

For posting the notifications...
To get the OpenFn Inbox URL, see OpenFn staging project inbox: https://www.openfn.org/projects/p5kaap/messages

NOTE: an auth key is required in the header all requests made to the inbox, so see this page and click `Reveal` to get the auth token: https://www.openfn.org/projects/p5kaap/access#add-new-security-protocol-btn
`"headers": {"x-api-key": "tokenInsert"},`

## adaptor
http (to post to OpenFn Inbox)

## expression.js
Can we write a script that will generate Message notifications to be sent to the OpenFn inbox at the same time (or milliseconds apart)? 

Using the sample state, create batch sizes of:
1. 20 messages
2. 50 
3. 100
4. 200
5. 400

We'll want to test each batch separate, to evaluate how the jobs and target system APIs perform when handling the traffic for each load. 

### output.json
For every 1 notification to be sent... a Message should be posted to the OpenFn inbox like this: https://www.openfn.org/projects/p5kaap/messages/0615c3e1-45f8-7d4c-98a9-20163f0e0a60

Therefore a batch of 20 notifications should send 20 individual Messages to the OpenFn inbox.

**Comment by aleksa-krolls** [comment]
@elias-ba @taylordowns2000 How's this going? Keep me posted if questions or if a quick chat this morning would be helpful.

If looking good, we can start testing in the OpenFn project `Primero Thailand IO [PROD]`. You both have access now. Please note that there will be a new Inbox security token. By noon UK time, I expect there to be little user activity in this project.

**Comment by taylordowns2000** [comment]
Great. All good on this side. Have both the load test script and the analysis working. We'll do one more batch of testing in staging and then at noon switch over to prod!

Analysis on github, but also as a saved question on Metabase: https://analytics.openfn.org/question/353-thailand-load-test-results

Please don't edit that question for now, will do some more tweaking before the prod run.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , this is ready to roll and i'm about to fire it up on prod.

https://analytics.openfn.org/question/353-thailand-load-test-results -  let me know if you have questions about how to analyze

**Comment by taylordowns2000** [comment]
Ready for your analysis @aleksa-krolls . So far, this is my reaction to [the results](https://analytics.openfn.org/question/353-thailand-load-test-results):

1. Primero is rate limiting us... see the [429 errors here](https://openfn.org/projects/pderjw/runs?dateRange=custom&endDate=2021-10-07T11%3A59%3A06.523Z&jobId=&page=1&perPage=10&searchString=&startDate=2021-10-07T11%3A50%3A02.000Z&success=1). And an explanation of `429` [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)
2. The HIS goes unresponsive sometimes... has this happened before? Looks like the run gets timed out waiting for a response.
3. The "get from HIS" takes 30 seconds! Why so long?
4. Either making these jobs use the same run, or making child runs higher priority should reduce lag, but a big part of the lag will still be the get runtime (see point 3).

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Tomorrow AM I'm going to write up a report summarizing this... so will have you review. But can you pls explain: 

1. What each `batch` was? I get the delay note, but does `1 req/case` mean that ultimately 20 total cases were sent? If yes re: `6/1/0.01`, was our largest batch size 120 cases (6*20 cases)? 

2. What these 2 columns are so I can interpret this more easily? Feel free to explain via VN if easier. 
![Screen Shot 2021-10-07 at 6.06.39 PM.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/e5ece6e3-9f89-4470-8b8f-21e666317b9e)

**Comment by taylordowns2000** [comment]
Hey @aleksa-krolls , good questions!

1. Batches starting with "p" are on prod and numbered from `00` to `N`, with that `c10` indicating that I turned up the concurrency to 10 before that batch. (It was set to 1 for `p01`.) There are 20 cases, so 1 request per case means a total of 20 requests made to OpenFn during the test batch. While I played around with different delays, I never increased beyond 20 cases to prod because even at that level we got timeouts from HIS and rate limiting from Primero. These things are outside our control, so we've got to sort them out before we can worry about making things go faster on the OpenFn side. (Which we can do, but doesn't make sense to do until the endpoints are able to handle more load.)

2. These columns are the average `exit_code` for r1 and r2 in the batch. `0` is success, `1` or higher is failure. I don't think we can properly load test until we see and average of `0` here (i.e., no failures) since anything above zero indicates that there were failures. When you see an average exit code above zero for a particular test, you should head over to the activity history page and analyze the individual failures for the time period of the test... this is how I found that Primero was rate limiting us and that HIS was timing out.

I think the report should start by asking for an investigation into the rate limiting and the timeouts. Once those are sorted out, then we can start turning up the juice... both testing with higher loads and making OpenFn process this stuff more quickly. Call my WhatsApp if you have any more questions tonight as I'll be on/off Slack for the rest of the day.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Tomorrow we need to send over to MOPH the logs of the HIS requests we sent (job run 1). I can send a link to filtered Activity History view... but do you think there's a Metabase report that would be better? 

Also, what are the best filters to apply to only see your all's load test runs? 
https://openfn.org/projects/pderjw/runs?dateRange=custom&endDate=2021-10-12T11%3A22%3A43.754Z&jobId=jy5jxn&page=1&perPage=10&searchString=&startDate=2021-09-12T11%3A22%3A35.719Z&success=

**Comment by taylordowns2000** [comment]
1. https://github.com/OpenFn/primero-thailand-load-testing/
2. https://analytics.openfn.org/question/353-thailand-load-test-results
