### ISSUE TITLE
Do not search HIS if no Patient `national_id` provided

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#26]
## Request
If no `data.national_id_no` provided in state, throw the error below and stop the flow... do NOT send a request to the HIS system. (Because if we don't filter HIS requests by a specific id, then the HIS responds with all patient data). 

`Error: Primero did not provide 'national_id_no'. Patient cannot be found.`

We need this `national_id_no` in order to filter HIS requests: 
```
filter = {
      where: { cid: formatNationalId(state.references[0].data.national_id_no) },
```
I added a temporary fix for now that will send the string `UNDEFINED`... but would be good to not even try searching the HIS and to log the specific message I outlined. 

## adaptor 
HTTP 

## expression
https://github.com/OpenFn/primero-thailand/blob/393eea61aa96e6373452be76c6f987d802864300/jobs/1-getPatientData.js#L28-L40

## state
Sample state: https://www.openfn.org/projects/pderjw/messages/0615cf99-de79-7b3f-9242-5112ea6a4831

**Comment by lakhassane** [comment]
@aleksa-krolls Im trying to test but can access the sample state here

**Comment by lakhassane** [comment]
Push a fix but can't test further without LP access and sample data.
