### ISSUE TITLE
Use `basic auth` in requests to Primero to avoid rate limiting

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#29]
## Background
We hit a 429 rate limiting error in the latest load testing. See example run failure: https://www.openfn.org/projects/pderjw/runs/0615ee05-1577-7dab-a8f3-7160b11a2506

## Request
Can you check that we're using basic auth for this job? (I thought we were... but maybe something needs to change in our adaptor?)

From the Quoin team: 
"""
Pavel says that, based on the linked OpenFn run, it looks like you're hitting the tokens interface every time you update a case. He suggests instead using basic auth on requests, since the tokens interface is rate-limited, but the Cases API shouldn't be

Another note: The tokens API only works when external identity is not being used. Basic Auth will always be guaranteed to work for the OpenFn user, regardless of identity implementation. This is another reason to use Basic Auth.
"""

## adaptor
primero

## expression
https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js

## state
See LP for `Primero Gambella open_function API user`
Feel free to use the related message from the parent Flow1 run & re-run on prod: 
https://www.openfn.org/projects/pderjw/messages/0615edfe-365e-7d1c-8e1f-7dc179b41c51

**Comment by aleksa-krolls** [comment]
@lakhassane and @elias-ba Tomorrow can you look at this together? Elias lead the load testing, but Mamadou wrote the original basic auth for the primero adaptor. 

cc @taylordowns2000 pls note this feedback from Quoin's investigation

**Comment by taylordowns2000** [comment]
@lakhassane , please refactor as discussed but leave everything in `generateAuthToken`, rather than leaving it all in `login`.

This is to say that `execute` should call `generateAuthToken` instead of calling `login`. Then, inside `generateAuthToken` on [line 51](https://github.com/OpenFn/language-primero/blob/64406ce2f94e49b697497f400a8dc9d0375b429b/src/Adaptor.js#L51) you should call `login`... this way, the output is always the correct `authToken` added to `state`. How that auth token gets generated (via a request to the `/api/token` endpoint or via base64 encoding of a `un:pass`) is irrelevant... and we only hit the API when `state.configuration.basicAuth` is `true`.

```js
  return state => {
    return commonExecute(
      generateAuthToken,
      ...operations,
      cleanupState
    )({ ...initialState, ...state });
  };
```

**Comment by aleksa-krolls** [comment]
@lakhassane please keep in mind this applies only to Primero V2 (not V1).

**Comment by lakhassane** [comment]
@taylordowns2000 check the PR on `language-primero` for this issue: https://github.com/OpenFn/language-primero/pull/34
One slight change in `login` is that we should now add the string `Bearer` in there because `generateAuthString` now does not return a string anymore but add the `auth` in `state`

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 Sounding good! keep me posted on: 
1. when this is live
2. configuration impacts- if adaptor versions need to be upgraded or the `configuration` changed 
3. what should be tested (should we re-run a load test?)
4. what to share back with Quoin/UNICEF

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @lakhassane please keep me posted on the questions above so I'm clear on next steps & what to communicate to the client. Thanks!

**Comment by lakhassane** [comment]
Hey @aleksa-krolls 
1. New adaptor released. Consider using: `v2.3.3`
2. no impact on configuration, you can still use the `basicAuth` with `true` or `false`
3. Yes you can re-run the same load to check if you will hit the 429 again
4. ... ? @taylordowns2000 ?

**Comment by aleksa-krolls** [comment]
@lakhassane should ALL primero V2 projects upgrade to this adaptor version?
