### ISSUE TITLE
Create 1 job to fetch field translations in Primero and post to the OpenFn inbox

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-thailand#31]
## Background, context, and business value

For this integration, we are syncing Primero case data to Child Shield, an AI software developed by the MOPH that ingests child health and protection data to determine what the child is at risk for. See issue #30 for more background information about 1) extracting case data from Primero and 2) loading the data to Child Shield. **This GH issue is for a step that should come in between steps 1 and 2 to translate the option values for select fields from English to Thai before sending them to CS .**

## The specific request, in as few words as possible
**See the [Data flow diagram ](https://lucid.app/lucidchart/b8ee8b9d-2f0f-4d19-b12e-908d4138ccb4/edit?beaconFlowId=64F72BCB10CA89B0&invitationId=inv_093b1b38-48bc-421c-a25e-0fbb5a1b7a8d&page=DUDNp3rsju.Q#)
![image](https://user-images.githubusercontent.com/80456839/188725544-85c09208-6d08-401b-ac6d-2d283a764b3e.png)** 

**Find the `lookup` name for each field via the `/forms` endpoint...**
1. Query `https://demo-care-thai-kids.primero.org/api/v2/forms/` using the credential listed in `state.json` below 
2. In the response, search for all 139 fields listed in the **select fields tab** of the [mapping specifications document](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit?pli=1#gid=954677598). Search for the fields using this path: `data[*].fields[*].name`
3. If a field is not found in the response, throw error with message `field ${fieldName} not found`
4. For each field that is found, find the value stored in key `option_strings_source`. These values will be used in the following steps. (Remove the first "lookup" before saving it in a variable `optionStringsSourceLookupName`). 
 Ex. if `"option_strings_source" = "lookup lookup-yes-no-unknown"`, capture `lookup-yes-no-unknown` for later use. 

**Find the option value ids & translations via the `/lookups` endpoint...**
6. Query `https://demo-care-thai-kids.primero.org/api/v2/lookups?per=1000000&page=1` using the credential below. This should return ALL available lookup records in 1 page.  
7.  The response will return an array of records (`data[*]`). Search the array for all of the `option_strings_source` values stored in step 4, looking for the object `data[*].unique_id` where `unique_id === ${optionStringsSourceLookupName}`
8. If lookup not found throw error and log message  `Options not found for lookup ${optionStringsSourceLookupName}`

**Generate a map of option value ids and translations...**
10. For each `optionStringsSourceLookupName`, generate a table which maps `data.values[*].id` to  `data.values[*].display_text.th` for each item in values. 
11. Post the resulting JSON object to the OpenFn Project Inbox as a `Message` that we can inspect to ensure the correct output was generated. 

**Desired mapping output**:
```
const optionStringsSourceLookupName = {
     data.values[*].id: data.values[*].display_text.th, //format
     "true": "ใช่",  //example
}
```
This^ displays `{option_value: translated_label } `

**For example**
If you performed the above steps for the field `disabilities_1`...
1. You would find [this json response ](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/forms_response_disabilities_1.json) in the `/forms` endpoint and notice that this field uses the `lookup-yes-no-unknown`
2. You would then find [these option values](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/lookup-yes-no-unknown.json) via the `/lookups` endpoint
3. The resulting mapping table you should generate for `disabilities_1` should look like this: 
``` js
 const yesNoUnknownMap = {
     "true": "ใช่", 
     "false": "ไม่ใช่",
     "unknown": "ไม่ทราบ"
}; 
```

## state.json
```json
{
  "configuration": {
      "url": "SEE LP for `Primero Thailand Demo API User (Open Function)`", 
     "user": "SEE LP for `Primero Thailand Demo API User (Open Function)`", 
     "password": "SEE LP for `Primero Thailand Demo API User (Open Function)`",
     "basicAuth": true,
     "openFnInboxURL": "Copy it from this page https://www.openfn.org/projects/primero-thailand-io-unicef---staging/settings"
  },
  "data": {}
}
```

## adaptor
See the [Primero API docs](https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api) for more on how to authenticate and access the different API endpoints. 

Note that we have a `language-primero` adaptor, but this currently does not have helper functions to access the `/lookups` and `/forms` endpoints. Therefore you may consider first testing this using `language-http`, but then adding new functions to the `language-primero` adaptor that can work with these new endpoints (e.g., `getForms(...)`, `getLookups(...)`

## trigger
Cron - Scheduled daily sync

## expression.js
Add the job to a new `child-shield` directory in this repo. 
Note: The output of this job will be used by the job which loads the case data to Child Shield. 

## output.json
We should have maps that look like this _for each_ of the lookups found for the 139 select fields. 
```js
const yesNoUnknownMap = {
     "true": "ใช่", 
     "false": "ไม่ใช่",
     "unknown": "ไม่ทราบ"
}; 
```

## Toggl 
`UNICEF Thailand`

**Comment by aleksa-krolls** [comment]
@mtuchi this is issue we discussed yesterday is ready to be worked on. @daissatou2 booked time on your calendar today to review this in detail, so please let her know if you have any questions. 
@taylordowns2000 flagging that this job may require changes to `language-primero` to work with new API endpoints - see our notes in the `adaptors` section of this issue.

**Comment by daissatou2** [comment]
@mtuchi discovered that certain select fields such as `conference_case_transfer_reason` have `option_strings_text`instead of `option_strings_source` in the `/forms` [response](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/option_strings_text.json). 

**`option_strings_text` is an array that captures the translations for the option values. We will not need to check the `/lookups` endpoint for these fields.** @mtuchi is seeing if he can implement the following:

1. For each field in the [select list](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit?pli=1#gid=954677598), check if it has `option_strings_source` in the `/forms` JSON response. If it does, follow the steps in the original GH issue. 
2. If it does not, check if it has `option_strings_text`
3. If it does not have `option_strings_text` either, log the error message "option values not found for field X"
4. If it has `option_strings_text`, generate a map of option value ids and translations as such: 
For each `optionStringsTextLookupName`, generate a table which maps data[*].fields[*].option_strings_text[*].id to data[*].fields[*].option_strings_text[*].display_text.th for each item in `option_strings_text`.

**Comment by mtuchi** [comment]
@taylordowns2000 i made some progress in this issue, i have pushed the progress ([See this PR](https://github.com/OpenFn/primero-thailand/pull/32))

**Comment by mtuchi** [comment]
> @mtuchi discovered that certain select fields such as `conference_case_transfer_reason` have `option_strings_text`instead of `option_strings_source` in the `/forms` [response](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/option_strings_text.json).
> 
> **`option_strings_text` is an array that captures the translations for the option values. We will not need to check the `/lookups` endpoint for these fields.** @mtuchi is seeing if he can implement the following:
> 
> 1. For each field in the [select list](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit?pli=1#gid=954677598), check if it has `option_strings_source` in the `/forms` JSON response. If it does, follow the steps in the original GH issue.
> 2. If it does not, check if it has `option_strings_text`
> 3. If it does not have `option_strings_text` either, log the error message "option values not found for field X"
> 4. If it has `option_strings_text`, generate a map of option value ids and translations as such:
>    For each `optionStringsTextLookupName`, generate a table which maps data[_].fields[_].option_strings_text[_].id to data[_].fields[_].option_strings_text[_].display_text.th for each item in `option_strings_text`.

Before i begin working on **Find the option value ids & translations via the /lookups endpoint** i want to work on this discovery. 
I want to store the response like this `field_name: option_strings_text` when `option_strings_source` is missing 

cc @taylordowns2000

**Comment by mtuchi** [comment]
@aleksa-krolls Quick feedback from my code review session with Taylor
since we're using `language-http` you `state.configuration` needs to be 

```
{
  "baseUrl": "adalshdlhl",
  "username": "usejals",
  "password": "iampassowrd",
  "basicAuth": true,
  "xApiKey": "",
  "openFnInboxURL": "Copy it from this page https://www.openfn.org/projects/primero-thailand-io-unicef---staging/settings"
}
```
cc @daissatou2

**Comment by aleksa-krolls** [comment]
@mtuchi says there are 2 errors that are being logged (but not yet thrown to force a job failure). [See example run](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0631f32f-1645-7274-bd11-a3bb7a77fa9b).  
1. Field not found in the `/forms` API response
E.g., `Error: field intervention_personal_type_needed not part of specified selectFields`
2. Lookup not found in the `/lookups` API response
E.g., `Could not find the value for: Location`

@daissatou2 can you please look into _why_ these errors might be happening in the first place and if we should adjust our job logic at all? There seems to be a lot. 

We eventually probably want to throw an error at the end of the job (with a list of ALL of these errors) if 1 or more of such scenarios are encountered, but let's first investigate why there are so many issues first.

**Comment by daissatou2** [comment]
@mtuchi I've moved this back to backlog per our discussion. See Slack [thread](https://openfn.slack.com/archives/C017ELVRSM8/p1662987214723259). 

The line [here](https://github.com/OpenFn/primero-thailand/blob/b5221ab8c47253059ccde7960c7d80fa94489578/jobs/child-shield/fetch_translations.js#L181) is logging an error if the field in the `/forms` response is not in the select list.

Please update the job to instead log an error if a field in the select list is not found in the `/forms` response. Please move this issue back to review when this is ready for testing.

**Comment by daissatou2** [comment]
@mtuchi it looks like the job is still logging an error if the field in the `/forms` response is not in the select list. See this run [log](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/063233a2-0f2f-71c7-9602-836bc4842a93).

The job _should not_ log an error if a field in the `/forms` response is not in the select list. **This is not an error case**--it is expected that there will be many fields in the `/forms` response that are not relevant for this integration (i.e. not in the select list). 

The [select list](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit?pli=1#gid=954677598&range=A2) contains all the fields which _are_ relevant for this integration and which need to be translated. Therefore, the job should log an error **if a field in the select list is missing in the `/forms` response**--because this means we will not be able to translate the field. For example, if the `location_current` field from the [select list](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit?pli=1#gid=954677598&range=A2) is missing from the `/forms` response, the job should log the error message "field location_current not found in forms response".

I've added time on your calendar tomorrow morning to sync on this in case there are more questions.

**Comment by daissatou2** [comment]
@mtuchi I see that there there was a PR here that wasn't merged...I've just merged and retesting now. Will keep you posted!

**Comment by daissatou2** [comment]
@mtuchi this is looking good for the `/forms` response! Please walk me through the error handling you implemented for the `/lookups` response during our sync tomorrow. I'm having trouble searching for these in the response manually...

**Comment by daissatou2** [comment]
This issue is pending a response from the client re: the handful of [fields](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06329099-f58c-7ce5-be60-26371df2e144) that are not in the `lookups` response. See slack [conversation](https://openfn.slack.com/archives/C017ELVRSM8/p1663599639700979).

**Comment by aleksa-krolls** [comment]
@daissatou2 see [my response](https://openfn.slack.com/archives/C017ELVRSM8/p1663661983334329?thread_ts=1663599639.700979&cid=C017ELVRSM8) and please spec the change requests and hand back to Mtuchi accordingly.

**Comment by daissatou2** [comment]
@mtuchi I have commented out the fields with `option_string_source` equal to `Agency`, `User`, or `ReportingLocation`. For now, we will not be translating these values. **Please implement the changes below for the Location fields.** 

I have removed the fields which have an `option_string_source` = `Location` from the select list in this job. The translations for all of these fields live in a separate `locations` endpoint. **Our job will query this endpoint once, generate a mapping table for location translations, and add the table to the final state which is posted to the OpenFn inbox.** Please follow the steps below: 

1. Query the `https://demo-care-thai-kids.primero.org/api/v2/locations?per=1000000` endpoint using the credentials listed above. 
2. Generate a `locationsMap` table  where for each location in the [reponse](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/locations_translations_lookup.json) (i.e each item in the `data` key), we map `data[].name.en` **:** `data[].[name.th]`. 
3. Add this `locationsMap` to the final state of this job.

**Comment by mtuchi** [comment]
> @mtuchi I have commented out the fields with `option_string_source` equal to `Agency`, `User`, or `ReportingLocation`. For now, we will not be translating these values. **Please implement the changes below for the Location fields.**
> 
> I have removed the fields which have an `option_string_source` = `Location` from the select list in this job. The translations for all of these fields live in a separate `locations` endpoint. **Our job will query this endpoint once, generate a mapping table for location translations, and add the table to the final state which is posted to the OpenFn inbox.** Please follow the steps below:
> 
> 1. Query the `https://demo-care-thai-kids.primero.org/api/v2/locations?per=1000000` endpoint using the credentials listed above.
> 2. Generate a `locationsMap` table  where for each location in the [reponse](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/locations_translations_lookup.json) (i.e each item in the `data` key), we map `data[].name.en` **:** `data[].[name.th]`.
> 3. Add this `locationsMap` to the final state of this job.

@daissatou2 this is done and ready for `review/QA`

**Comment by daissatou2** [comment]
@taylordowns2000 please make this a long-running [job](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/jobs/zXxiCH) on platform. It is currently [timing out](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0632d25c-1e7b-7040-8704-fe5f97c1bd72).

**Comment by aleksa-krolls** [comment]
@mtuchi today please see what you can do to optimize this job. See my [Slack comments](https://openfn.slack.com/archives/C03EQQB5W7R/p1663909460971959?thread_ts=1663903621.764369&cid=C03EQQB5W7R)
