### ISSUE TITLE
Update job `1b-upsertCases.js` to load PLH and Risk Data to Primero

### ISSUE THREAD

**Issue by jayesse** [OpenFn/unicef-thailand#33]
## Background, context, and business value

We have more complete mappings for upserting cases in Primero with data retrieved from HIS. The mappings are not entirely complete but we are only expecting additional fields and no structural changes. See the last round of updates in issue #3 .

In the current production implementation...
1. Primero case updates will sometimes trigger a webhook to send a notification to OpenFn. 
2. OpenFn then checks the Thailand HIS API for this person's medical records, and syncs back to Primero to give the caseworker access to the person's full medical history (see step `Sync HIS data to Primero case & subforms` in the below diagram). 
We want to extend this implementation to map additional data points in this `Sync HIS data` step in order to map this data to new "Child Shield" forms in Primero. 
![Thailand Primero __ HIS data flow  2021 Phase 1- Live Solution  - CLEANED_ Integration flow phase 1](https://user-images.githubusercontent.com/16758106/192786713-8a4b8897-9fe9-4bba-9e3f-a44f46a69f40.png)

## The specific request, in as few words as possible
As Part of Phase 2 of the UNICEF Thailand integration, there is a need to transform, map and load additional data (_PLH_ and _Risk Model_) to Primero cases. 

### Data Flow Diagram
We have an updated data flow diagram capturing the expanded logic for this project phase: https://lucid.app/lucidchart/b8ee8b9d-2f0f-4d19-b12e-908d4138ccb4/edit?beaconFlowId=64F72BCB10CA89B0&invitationId=inv_093b1b38-48bc-421c-a25e-0fbb5a1b7a8d&page=jdJOhMkaAPqa#

### Mapping Considerations
**Mapping Specs** can be found in the _Flow2_ChieldShield -> Primero_vOpenfn_ of this [Mapping document](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=1877091315).

- Where any of the values above are missing the mapping information is still incomplete, please ignore for the time being.
- We did not provide exact paths to the source dataValues, but rather unique attributes (see specs columns `C`, `D`, and `F`) that will help us search for the unique `question_name`... and then locate the answers we need to map as dataValues to Primero. **See related Slack thread where we discussed mapping logic to search the JSON for unique questions:** https://www.google.com/url?q=https://openfn.slack.com/archives/C017ELVRSM8/p1663845613114939?thread_ts%3D1663845007.366889%26cid%3DC017ELVRSM8&sa=D&source=editors&ust=1664374716287472&usg=AOvVaw1dpLObKd-6Qfe6ncOTU2fg
- To understand the logic for mapping answers for different question types (e.g., where we check which answer is 'checked=true` for `select` questions), please see this [diagram for how to map & transform answers](https://lucid.app/lucidchart/b8ee8b9d-2f0f-4d19-b12e-908d4138ccb4/edit?view_items=kJcVxi5efmj-&invitationId=inv_093b1b38-48bc-421c-a25e-0fbb5a1b7a8d#). 

## expression.js
**⚠️ Make all changes on `staging` branch; do NOT commit to Master.** 
Update existing job:  `jobs/1b-upsertCases.js`

This job already has 1 `upsertCase` operation and sends a json object called `data` in the request sent to the Primero API ([see L617](https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js#L614-L617). We want to extend the mappings for this case `data` object in order to _also_ map PLH and riskmodel data. 

NOTE: This job is a flow job triggered by `1-getPatientData.js`. 

## state.json
To generate state for this job...
1. First run job 1-getPatientData.js` to generate state for the flow job we need to update:
- `state.data`: Use [this payload](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/childShield/primeroSyncNotification_cid_1111111111113.json) as `state.data`for the first flow job: [1-getPatientData.js](https://github.com/OpenFn/primero-thailand/blob/master/jobs/1-getPatientData.js). 
- `state.configuration`: see LP `MOPH Thailand HIS API - DEMO Alpha (Unicef)`

---> This^ will return a large json response that looks [like this](https://raw.githubusercontent.com/OpenFn/primero-thailand/master/sampleData/childShield/Risk_model_PLH_data_OFG.json). 

2. For the job `1b-upsertCases.js` we need to update:
- `state.data`: Use the final state of the first job 
- `state.configuration`: see LP `Primero Thailand Demo API User (Open Function)` (Note... this user is for **basic auth**.)

## adaptor

1. `1-getPatientData.js`: `language-http` to connect to HIS API (see relevant HIS API docs: https://docs.google.com/document/d/1GIRxVXSZLgmKwTf-dP0kQjto5-VdZl5GjCj-pAjKfaA/edit)
2. `1b-upsertCases.js`: `language-primero` to connect to Primero v2 API (see docs: https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api/v2/docs )

## trigger
Flow job
[`When job 1.a. Get Patient from HIS succeeds.`](https://www.openfn.org/projects/p5kaap/triggers/t9zjdb)

## output.json
Example output for Primero case: https://github.com/OpenFn/primero-thailand/blob/master/sampleData/childShield/getPrimeroCaseWithChildShieldForms.json

- Follow the mapping specs for how to map such Primero case fields, and see the data flow diagrams for how the mapping logic changes depending on whether the question type is `select`, `string`, `date`, etc. 
- For example if we receive marrystatus: "4" from HIS, we will ultimately map the case value `maritial_status: "divorced"` to Primero.

### side effects
Upsert 1 case record in Primero using the Primero `record_id` received in the notification that triggers the first flow job (e.g. `"record_id": "f173296b-0e06-4603-8690-500907c7fe37"` - [see L31](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/childShield/primeroSyncNotification_cid_1111111111113.json#L31)) as the externalId.

**Comment by aleksa-krolls** [comment]
@jayesse I updated [this Jobs Flows diagram](https://lucid.app/lucidchart/b8ee8b9d-2f0f-4d19-b12e-908d4138ccb4/edit?viewport_loc=-270%2C-26%2C3117%2C1500%2CnEyQdSFm_Akd&invitationId=inv_093b1b38-48bc-421c-a25e-0fbb5a1b7a8d#)... for you to analyze the existing jobs and confirm, but this Child Shield `Flow 2` might extend the existing jobs from the Phase 1 implementation? Not sure whether we need to write any new jobs, but keep me posted if you think there's a good argument for that

**Comment by jayesse** [comment]
@aleksa-krolls Please review the issue and the updated logic diagram for handover to Mtuchi.

**Comment by aleksa-krolls** [comment]
@mtuchi this is the other Thailand data flow we discussed briefly with you and Taylor last week (the one with the very big JSON response). When you pick it up tomorrow, let @jayesse know if you have any questions!

**Comment by mtuchi** [comment]
@jayesse 

1. PLH and Risk Model Data, how do i get  the data ? 1-getPatientData.js returns interventions only for now, Do i need to modify to get PLH and risk model data ?
2. Is the mapping spec only for PLH and risk model data? If so, how do I filter only PLH mapping or risk model data mapping in that spreadsheet?
3. This sample output (https://github.com/OpenFn/primero-thailand/blob/master/sampleData/childShield/getPrimeroCaseWithChildShieldForms.json) Can you show me what is added and what already exists in the job? 
cc @aleksa-krolls

**Comment by mtuchi** [comment]
I created a mapping spec that helps filter between first-week assessment and 14 week assessment data, the work in progress can be found in this PR #57 
cc @jayesse @aleksa-krolls

**Comment by mtuchi** [comment]
I have created the mapping for `PLH data` and `Risk model` data, Some of the fields are returning `null`. These are the fields that are either missing from the `API` or are not found. I have merged changes ➡️  #57 for testing.
@daissatou2 @jayesse please leave the feedback and will work on them tomorrow

**Comment by aleksa-krolls** [comment]
@mtuchi We ran this on platform and it failed. 
1. On platform, [this Message](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/06344467-d9da-7176-b37d-15e1ebc9d590) was processed successfully. 
2. But the second job `1b-upsertCases.js` failed with error `RangeError [Error]: Invalid time value`
https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06344471-06e3-76b1-9509-c8f1d16ca3b4

I've copied the Message that @daissatou2 created by clicking the sync button in Primero to trigger `1-getPatientData.js` into this Github file for you to test locally: https://github.com/OpenFn/primero-thailand/blob/staging/sampleData/test_job1_10102022.json

cc @jayesse

**Comment by mtuchi** [comment]
> @mtuchi We ran this on platform and it failed.
> 
> 1. On platform, [this Message](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/06344467-d9da-7176-b37d-15e1ebc9d590) was processed successfully.
> 2. But the second job `1b-upsertCases.js` failed with error `RangeError [Error]: Invalid time value`
>    https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06344471-06e3-76b1-9509-c8f1d16ca3b4
> 
> I've copied the Message that @daissatou2 created by clicking the sync button in Primero to trigger `1-getPatientData.js` into this Github file for you to test locally: https://github.com/OpenFn/primero-thailand/blob/staging/sampleData/test_job1_10102022.json
> 
> cc @jayesse

I have push a fix for this error on #58, you can now test the job on platform-app cc @jayesse @aleksa-krolls

**Comment by mtuchi** [comment]
Fix missing maps #60 cc @aleksa-krolls @jayesse

**Comment by jayesse** [comment]
@mtuchi All my subsequent tests were successful, and I have handed over the job to the client for testing. Thanks for all your help. I'm closing this issue now.
