### ISSUE TITLE
1d-sendPrimeroFailureStatus.js: fails when case closed & no services defined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#36]
## Describe the bug
Error when client tested "closing" cases. 
`TypeError: Cannot read property 'services_section' of undefined`
https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/063227b0-873a-79c5-8f36-5023faae26f2

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: __________

### expression.js
Link to the job itself in Github: _____________

### state.json

Either provide state directly, or link to a file. If sensitive information
should be in state, redact it and provide instructions for where it can be
found.

```json
{
  "configuration": ["SEE LAST PASS: 'client cred'"],
  "data": { "a": 1 },
  "cursor": "2020-01-19 00:00:00"
}
```

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by re-running this run (link) and confirming success.]

## Toggl 
Name of the Toggle project to log work

**Comment by jayesse** [comment]
@aleksa-krolls Is there anything left to be done here?

**Comment by aleksa-krolls** [comment]
Addressed in phase 2 implementation.
