### ISSUE TITLE
Job #3 to map translated case data & sync with Child Shield

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#47]
## Background, context, and business value
See issues #30 and #31 for more background on the job1 and job2 that we created to get case data from Primero and then get translations from Primero. Now we want to use these to map `case` data _with_ translated values to Child Shield, and perform a series of operations in the Child Shield API to confirm the Primero `case` isn't already saved as an existing `intervention`. 

<img width="838" alt="Screen Shot 2022-09-28 at 8 47 43 AM" src="https://user-images.githubusercontent.com/16758106/192697828-bfd7ed15-973b-473e-8e2d-65366c6a594c.png">

## The specific request, in as few words as possible
Job3 will sync map & data to Child Shield.  
1. This job will be a flow job, so its initial state will be the Primero cases from job 1 and the translation mappings from job 2 (#31).
2. Map the cases to Child Shield according to the [mapping specifications](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit?pli=1#gid=541136337) `[Phase2_Flow1] Primero -> Child Shield _vOpenfn` tab. For all **[select fields](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=954677598)**, use the translation mappings (job 2) to translate the option values before loading to Child Shield. 
3. Check if intervention already exists in CS using `cid`:`national_id`(see `national_id `in Primero case data). `GET /interventions/findOne?access_token=TOKEN`. See sample [payload](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/childShield/get_intervention_data.json).
4. If the intervention _does_ exist (i.e you get a 200 response from step 3), update the existing intervention using the `id` from the GET response in step 3. `PATCH /interventions/{id}?access_token=TOKEN`. See sample [payload](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/childShield/edit_intervention_data.json). See the API docs below for how to format the request using the mapping specifications. 
5. If the intervention does _not_ exist, check if the person record already exists using `"cid": national_id`(see `national_id `in Primero case data). `GET /people/findOne`. See sample [payload](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/childShield/get_people_findOne.json). 
6. If the person does _not_ exist, fail and log error "Person does not exist".
7. If the person _does_ exist, create a new intervention for the person `POST /interventions`. See sample [payload](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/childShield/create_intervention_data.json). See the API docs below for how to format the request using the mapping specifications. 
**Note**: We do not have the full JSON path for each field being mapped to Child Shield; we only have the field name or "matching attribute" (column H in mapping spec). For each field, this job should search through the inbound payload from job 1 and grab the value for the matching attribute. See slack [thread](https://openfn.slack.com/archives/C017ELVRSM8/p1660596219397849) and  TD's suggested code below. 

### Mapping Considerations
**Note**: We do not have the full JSON path for each field being mapped to Child Shield; we only have the field name or "matching attribute" (column H in mapping spec). For each field, this job should search through the inbound payload from job 1 and grab the value for the matching attribute. See slack [thread](https://openfn.slack.com/archives/C017ELVRSM8/p1660596219397849) and  TD's suggested code below. 

**From the mapping specs, use Column `H` as the unique key to search in the JSON for the matching attribute, and column `M` the destination JSON path. See API docs and data flow diagram for links to sample POST and PATCH payloads**

``` js
function lookup(obj, k) {
  for (var key in obj) {
    var value = obj[key];

    if (k == key) {
      return [k, value];
    }

    if (typeof(value) === "object" && !Array.isArray(value)) {
      var y = lookup(value, k);
      if (y && y[0] == k) return y;
    }
    if (Array.isArray(value)) {
      // for..in doesn't work the way you want on arrays in some browsers
      //
      for (var i = 0; i < value.length; ++i) {
        var x = lookup(value[i], k);
        if (x && x[0] == k) return x;
      }
    }
  }

  return null;
}
```

```js
function type(object) {
  var stringConstructor = "test".constructor;
  var arrayConstructor = [].constructor;
  var objectConstructor = {}.constructor;

  if (object === null) {
    return "null";
  } else if (object === undefined) {
    return "undefined";
  } else if (object.constructor === stringConstructor) {
    return "String";
  } else if (object.constructor === arrayConstructor) {
    return "Array";
  } else if (object.constructor === objectConstructor) {
    return "Object";
  } else {
    return "null";
  }
}
```

Example HTTP request body when sending a `POST` to Child Shield API: 
``` js
{
    "hcode": "10671",
    "national_id": "60377a0b08dda916ba73874b",
    "ovstist": "primero",
    "vstdate": "2022-08-08",
    "vsttime": "20:16:36",
    "hname": "รพ.อุดรธานี",
    "activities": {
        "primeroservice": {
            "serviceType": "primero",
            "24-08-2022": { //date to be dynamically  updated to = todaysDate
                "formsection-patient-education-and-career-6d53ca5": { //Primero form name
                    "email_address": "test@openfn.org", //Primero field name + value
                    "occupation_1": {  //Primero field name
                        "pre_school": "ก่อนวันเรียน"  //selected option value + translated value
                    }
                },
                "form2": { //Primero form name
                    "f2question": "answer" //Primero field name + value
                },
                "form3": {
                    "f3question": "answer:" //Primero field name + value
                }
            }
        }
    }
}
```
### Data Flow Diagram
[**DATA FLOW DIAGRAM**](https://lucid.app/lucidchart/b8ee8b9d-2f0f-4d19-b12e-908d4138ccb4/edit?beaconFlowId=64F72BCB10CA89B0&invitationId=inv_093b1b38-48bc-421c-a25e-0fbb5a1b7a8d&page=gz2GymXUIyeW#)

<img width="929" alt="Screen Shot 2022-09-28 at 8 53 05 AM" src="https://user-images.githubusercontent.com/16758106/192699802-47fa44e1-1078-4eca-9301-480bc1d5d8ed.png">

## state.json
Run jobs 1 and then 2 to generate an initial state for this new job. When running Job 1, you can use the manual cursor. 

JOB 1 - **Use the manual cursor; you should see at least cases with `case_id_display` [d59eaa8](https://demo-care-thai-kids.primero.org/v2/cases/f173296b-0e06-4603-8690-500907c7fe37) and [abecba4](https://demo-care-thai-kids.primero.org/v2/cases/96493cbe-aa9c-467e-b71f-fb1aa75e7426) returned.**
```json
{
  "configuration": { "SEE LP Primero Thailand Demo API User (Open Function)" },
  "cursor": "Fetch cases where "last_updated_at" >= ''2022-09-28T00:43:07.000Z'"
}
```

JOB 2:
```json
{
  "configuration": ["See LP MOPH Thailand HIS API - DEMO Alpha (Unicef)'"],
  "data": { "data generated by GET job"},
}
```

JOB 3:
```json
{
  "configuration": ["See LP MOPH Thailand HIS API - DEMO Alpha (Unicef)'"],
  "data": { "final state of last 2 jobs"},
}
```

## adaptor
Job 1: language-primero 
Job 2: language-http
**Job 3: language-http**

### API Docs
1. [Child Shield API docs](https://docs.google.com/document/d/1GIRxVXSZLgmKwTf-dP0kQjto5-VdZl5GjCj-pAjKfaA/edit#heading=h.54fpob4z8r60)
2. [Child Shield Sample Postman Requests](https://docs.google.com/document/d/1GIRxVXSZLgmKwTf-dP0kQjto5-VdZl5GjCj-pAjKfaA/edit#)
3. [Primero API docs](https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api)

## trigger
Job 1: Cron
Job 2: Flow
**Job 3: Flow**

## expression.js
Add new file `syncToChildShield.js` to directory `/jobs/child-shield`

## Toggl 
`UNICEF Thailand`

**Comment by aleksa-krolls** [comment]
@mtuchi this job#3 is finally ready to be worked on! Please pick it up whenever you're free next. I will be free around 12p if you want to discuss, and @daissatou2 should be online later this afternoon if you have ampping questions.

**Comment by aleksa-krolls** [comment]
@mtuchi as discussed, to help you understand what the final JSON output should look like...
1. Let's say today you ran the Job1 `getCasesFromPrimero.js`, and the Primero API returned [this case](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/childShield/getPrimeroCaseWithChildShieldForms.json)
2. Then you ran Job2 `fetch_translations` to get translations for all select questions
3. When mapping Job3, your mappings for the `basic_identity` form (rows 5-13 in the [mapping spec](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=541136337)) should ultimately output a JSON payload like this...
https://github.com/OpenFn/primero-thailand/blob/a42b56b2a445ab32bc41818e8e67b2d9e4d25237/sampleData/childShield/sampleBodyPOST.json#L11-L22
...where the date `28-09-2022` = todaysDate, `basic_identity` is the form name, which is a JSON object that contains a list of its related fields and translated values, if the field is a `select` question. 

**For now, if a field isn't available in the getCases Job1 response (e.g., `address_of_accomodation__foreigners_only_`), send a `null` value to Child Shield.**

**Comment by daissatou2** [comment]
@mtuchi if a field in the mapping specifications **is missing from the Primero** `getCases()` response, let's send `null` to Child Shield like line 20 in this sample [payload](https://github.com/OpenFn/primero-thailand/blob/a42b56b2a445ab32bc41818e8e67b2d9e4d25237/sampleData/childShield/sampleBodyPOST.json#L20).

If a field **is in the getCases() response but has a value of empty string** `""`, we should send the empty string to Child Shield. For example, if we get `"other_id_no": ""` from Primero, we should send `"other_id_no": ""` to Child Shield.

**Comment by mtuchi** [comment]
> ## The specific request, in as few words as possible
> Job3 will sync map & data to Child Shield.
> 
> 1. This job will be a flow job, so its initial state will be the Primero cases from job 1 and the translation mappings from job 2 ([Create 1 job to fetch field translations in Primero and post to the OpenFn inbox #31](https://github.com/OpenFn/primero-thailand/issues/31)).
> 2. Map the cases to Child Shield according to the [mapping specifications](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit?pli=1#gid=541136337) `[Phase2_Flow1] Primero -> Child Shield _vOpenfn` tab. For all **[select fields](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=954677598)**, use the translation mappings (job 2) to translate the option values before loading to Child Shield.

- [x] This job will be a flow job, so its initial state will be the Primero cases from job 1 and the translation mappings from job 2 (https://github.com/OpenFn/primero-thailand/issues/31).
- [x] Map the cases to Child Shield according to the [mapping specifications](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit?pli=1#gid=541136337) [Phase2_Flow1] Primero -> Child Shield _vOpenfn tab. For all [select fields](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=954677598), use the translation mappings (job 2) to translate the option values before loading to Child Shield.

The first two task are done, See #49 (If merged you can test on platform-app to see the results)

I will pick up task 3, 4, ... tomorrow cc @aleksa-krolls @daissatou2

**Comment by mtuchi** [comment]
A work in progress PR https://github.com/OpenFn/primero-thailand/pull/51, for mapping translations to be sent to child shield,
A blocker I have at the moment, I can't catch a `404` error when interventions do not exist,I will pick up this on Monday to fix that issue cc @aleksa-krolls @taylordowns2000 @daissatou2

**Comment by daissatou2** [comment]
@mtuchi moving this to backlog. Reach out with any questions! 

**Mapping feedback:**
1.  Please review the data being sent to CS using the logs. Case with `cid` 1400800050937 and `case_id` 3e9e42b4-7139-4746-822a-12ad02534643 is a good one to test with because I filled in data for all the fields in Primero for that case. You can compare the logs for what is received from [Primero](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0633b65e-b832-7f0f-a2e2-eed4b0c3508b), to what you're [sending to CS](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0633b65f-9403-7266-ad66-2bc3cec5c8ed). **Use these run logs to take a look at numbers 2 and 3 below.**
2. `relation_nationality` only has the option-value `Thailand`  in Primero,  however we are sending all locations to CS. I’m seeing this pattern of sending ALL option values to CS instead of just the selected values for many other fields (ex. `risk_level`, `status`, etc). **We should only send the option values that were selected in Primero, i.e. reflected in the `getCases` response from Job 1.** 
3. We are sending `null` for all fields in several forms (like `physical_check_2` and `conference_details_container`). The fields for these forms have data in Primero. **We should only be sending `null` if the field is missing from the Primero getCases() response.** 


**Other feedback:**
1. When I run a `get` `/interventions/findOne` for `cid` 1400800050937 I am seeing data for `2022-10-03` twice...see the two images below. The first one is from when we `POST` the intervention and the second one shows up after we PATCH the intervention.  It looks like we are sending the wrong payload for the `PATCH `so it's creating a duplicate instead of updating the existing one. 
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/80456839/193707505-27b074b2-a777-4140-810c-1e326c1c56c5.png">

<img width="1044" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/80456839/193708515-63c91645-5d34-443f-947f-97dfcc9b8719.png">


New test data for POSTing interventions with `manualCursor = '2022-09-30T00:43:07.000Z'`
- `cid` 1409800599546 `case_id` af4b7c73-ed91-4cd3-9f7c-f45f3d59eaa8
- `cid` 1417500145998 `case_id` 7d64540c-28f4-4361-95bd-d8252feac0bc

**Comment by mtuchi** [comment]
@daissatou2 I have worked on your feedback and merged the changes on this PR #52, The pending items are the missing forms and form fields

**Missing forms & fields**
`final_diagnosis_3696c45` (this is a missing field)
`witnesses__6c0a3 -> witnesses__6c0a33c` (missing form & what is suppose to be)
`conference_details_container -> conference_details_subform` (missing form & what is suppose to be)
cc @aleksa-krolls

**Comment by daissatou2** [comment]
@mtuchi please review why the three fields below are null in the [formMap](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0633db26-2621-7d9e-a264-c456f632bc2c) but are in the getCases [response](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0633db25-32c7-7d6c-8113-40cbeba461d1) for `case_id` 3e9e42b4-7139-4746-822a-12ad02534643. 
- `specify_legal_offenses`
-  `specify_physical_issue`
- `If_abnormal__please_specify_1`

Also I am not seeing the forms for `witnesses__6c0a3 -> witnesses__6c0a33c` & `conference_details_container -> conference_details_subform` in the formMap. Were they removed? We will flag to the client that the form name was not what's in the mappings for those two fields but can you please make sure they are still in the formMap since we've learned what the names should be?

**Comment by daissatou2** [comment]
@mtuchi as discussed, please update Job 3 to fail if a person is not found. See this run [log](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0633dca6-6c17-7732-9554-7eb60c957540) for example where the job currently passes. 

You can test with `case_id` af4b7c73-ed91-4cd3-9f7c-f45f3d59eaa8, `cid` 114462302779. This person does not exist in Child Shield.
