### ISSUE TITLE
Requests to Primero failing with `Error: unable to verify the first certificate`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#63]
## Describe the bug
[See run failure](https://www.openfn.org/projects/primero-thailand-io-prod/runs/063469aa-342e-72b0-87d8-484e0a9b11df) with error: 
```
Error: unable to verify the first certificate

    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)

    at TLSSocket.emit (node:events:513:28)

    at TLSSocket._finishInit (node:_tls_wrap:952:8)

    at ssl.onhandshakedone (node:_tls_wrap:733:12) {

  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
  ```

## To Reproduce
This is a prod project, so I cannot provide real data to replicate. Can you try using the Primero adaptor to authenticate or run a `getCases(...)` request to see if you can reproduce? 

### expression.js
Fails when this job [master/jobs/1b-upsertCases.js](https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js) runs... but NO changes should be made. This is definitely an auth/adaptor issue. 

### state.json
Taylor or Aleksa only can access in LP - see slack: https://openfn.slack.com/archives/C017ELVRSM8/p1665572511318539?thread_ts=1665571807.403209&cid=C017ELVRSM8

## adaptor
`language-primero@2.3.4`

**Comment by taylordowns2000** [comment]
@aleksa-krolls , in review waiting on Primero's response. I've sent details in Slack: https://openfn.slack.com/archives/C017ELVRSM8/p1665573406571529?thread_ts=1665571807.403209&cid=C017ELVRSM8

**Comment by aleksa-krolls** [comment]
Resolved. Client reconfigured the SSL certification to resolve.
