### ISSUE TITLE
Enhance logging when HTTP requests to Primero fail

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#72]
## Background, context, and business value

See [this recent run](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0634ecdf-01ae-7e07-8c96-7138cc82cee7) with the `EAI_AGAIN` error that fails at login step. 

And see [this 2nd example](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0634ed03-8426-7997-a261-ebe9ed5844ea) that fails at next step after login successful. 

## The specific request, in as few words as possible
I've shared with the client, but to help them better troubleshoot, **when the request fails** it would be great if I could see the full details on the HTTP request we're sending (what method, URL, request body, etc.) in the run logs.  

## state.json
```json
{
  "configuration": {
      "url": "SEE LP for `Primero Thailand Demo API User (Open Function)`", 
     "user": "SEE LP for `Primero Thailand Demo API User (Open Function)`", 
     "password": "SEE LP for `Primero Thailand Demo API User (Open Function)`",
     "basicAuth": true,
     "openFnInboxURL": "Copy it from this page https://www.openfn.org/projects/primero-thailand-io-unicef---staging/settings"
  },
  "data": See this Message: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/0633af02-fa1c-77f1-86c4-3cd6f50dfe36
}
```

## adaptor
language-primero latest

## trigger
You can try reproducing the error by running the job against [this Message](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/0633af02-fa1c-77f1-86c4-3cd6f50dfe36). 

## expression.js
https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1-getPatientData.js

## output.json
An error like below where I can see the full `url` and `method`... as well as `body` is preferred. 
```
Error: getaddrinfo EAI_AGAIN cloud1-r8way.moph.go.th
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'cloud1-r8way.moph.go.th',
  config: {
    url: 'https://cloud1-r8way.moph.go.th:3011/api/Users/login',
    method: 'post',
```

## Toggl 

UNICEF Thailand

**Comment by mtuchi** [comment]
@aleksa-krolls 
This error 👇🏽 , Was due to `cloud1-r8way.moph.go.th` nameservers not being properly set 
```
Error: getaddrinfo EAI_AGAIN cloud1-r8way.moph.go.th
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'cloud1-r8way.moph.go.th',
  config: {
    url: 'https://cloud1-r8way.moph.go.th:3011/api/Users/login',
    method: 'post',
```
But it looks like they have already solved this issue 👇🏽 
https://mxtoolbox.com/SuperTool.aspx?action=a%3acloud1-r8way.moph.go.th&run=toolpage

So right now I can't reproduce the error so that I can properly catch it and display the logs

**Comment by aleksa-krolls** [comment]
@mtuchi  Maybe we can't reproduce this error... but we can force another. Can you please deliberately remove the password or something from the configuration and then run the job to force an auth error? Then make sure that what the OpenFn run logs is detailed enough (includes url, method, request body)

**Comment by mtuchi** [comment]
> @mtuchi Maybe we can't reproduce this error... but we can force another. Can you please deliberately remove the password or something from the configuration and then run the job to force an auth error? Then make sure that what the OpenFn run logs is detailed enough (includes url, method, request body)

@aleksa-krolls if I remove the password it will be a different error and not `Error: getaddrinfo EAI_AGAIN`, The error above is due to bad server setup

**Comment by aleksa-krolls** [comment]
@mtuchi yes, understood... but I suspect logging is not good for _any_ error, not just this `EAI_AGAIN` one. 

See [this run failure](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/063510bf-e3de-7706-a917-2fa98b7ee0be) I forced by adding false characters to the destination `url`. See how the logging doesn't tell me much about the request I was trying to make? Can you please add/remove characters from the `url` value in your configuration and test to see if you can enhance the logging for such scenarios where the job fails at the authentication/login step? 
```
Error: getaddrinfo ENOTFOUND cloud1-r8way.moph.go.t
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'cloud1-r8way.moph.go.t'
}
```

**Comment by mtuchi** [comment]
@aleksa-krolls 
I have improved error logging, see #74 

⚠️  This update requires `language-http@v4.0.0`, It was tested in the environment 👇🏽 
```
╭─────────────────────────────────────────────╮
│ ◲ ◱  @openfn/core#v1.4.8 (Node.js v18.10.0) │
│ ◳ ◰             @openfn/language-http@4.0.0 │
╰─────────────────────────────────────────────╯
```
