### ISSUE TITLE
1b-upsertCases.js: TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#75]
## Issue
Seeing run failures on prod with message: `TypeError: Reduce of empty array with no initial value`
https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06352482-204a-725e-9942-b88e27f928ec

## How to replicate
1. Run Job1 with this data: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/0635247f-dd71-79ad-a6c0-e3bb66588130
2. Use final state of this^ for Job2

## state.json

JOB1: 
configuration: See LP for `MOPH Thailand HIS API - DEMO Alpha (Unicef)`

JOB 2: 
```json
{
  "configuration": {
      "url": "SEE LP for `Primero Thailand Demo API User (Open Function)`", 
     "user": "SEE LP for `Primero Thailand Demo API User (Open Function)`", 
     "password": "SEE LP for `Primero Thailand Demo API User (Open Function)`",
     "basicAuth": true,
     "openFnInboxURL": "Copy it from this page https://www.openfn.org/projects/primero-thailand-io-unicef---staging/settings"
  },
  "data": See this Message: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/0633af02-fa1c-77f1-86c4-3cd6f50dfe36
}
```

## adaptor
language-primero latest

## expression.js
Please push changes to `staging` branch
https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js

## output.json
Successful run & upsert of case in Primero

## Toggl 

UNICEF Thailand

**Comment by jayesse** [comment]
@mtuchi What's the status here? Have you been able to apply the fix?

**Comment by mtuchi** [comment]
> @mtuchi What's the status here? Have you been able to apply the fix?

@jayesse #77 this fixes the error and `logs` question with invalid `answersList`

**Comment by aleksa-krolls** [comment]
@jayesse can we please close out this issue given that TypeErrors are resolved? I think we're waiting for the client on new things now, yeah?

**Comment by jayesse** [comment]
Issue resolved. Thanks team.
