### ISSUE TITLE
1b-upsertCases.js: `Invalid record JSON` error for `severity_type_323dfc7`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#76]
## Issue
Seeing run failure: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06352459-ede0-72eb-bd00-6b3dd6f398f2

What's also problematic is that the logs don't show what the case data is that we're sending to Primero before the error is thrown. Can you please troubleshoot and then add back in console.logs to log the request body before we send to Primero? 

## How to replicate
1. Run Job1 with this data to trigger the low: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/06352459-6ff4-7a82-9481-000ba4c89956
2. Use final state of this^ for Job2

## state.json

JOB1: 
configuration: See LP for `MOPH Thailand HIS API - DEMO Alpha (Unicef)`

JOB 2: 
```json
{
  "configuration": {
      "url": "SEE LP for `Primero Thailand Demo API User (Open Function)`", 
     "user": "SEE LP for `Primero Thailand Demo API User (Open Function)`", 
     "password": "SEE LP for `Primero Thailand Demo API User (Open Function)`",
     "basicAuth": true,
     "openFnInboxURL": "Copy it from this page https://www.openfn.org/projects/primero-thailand-io-unicef---staging/settings"
  },
  "data": Job1 final state
}
```

## adaptor
language-primero latest

## expression.js
Please push changes to `staging` branch
https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js

## output.json
Successful run & upsert of case in Primero

## Toggl 

UNICEF Thailand

**Comment by aleksa-krolls** [comment]
@mtuchi here's another bug to pick up next. 
cc @jayesse

**Comment by jayesse** [comment]
@mtuchi Concerning the `severity_type_323dfc7` error, here's what I observed: 

In this [Case Sync Request run log](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06352646-2041-73d7-a543-e9ef1b8a9483) (cid `1439200005793` ), the `severity_type_323dfc7` is an array:
```
"riskLevel": "high",
        "severityType": [
            "ทางเพศ",
            "ทางจิตใจ"
        ],
        "sex": "หญิง",
```

However, in the [job script](https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js#L2911-L2918) I'm not sure if the data is being sent as an array into Primero

**Comment by mtuchi** [comment]
> @mtuchi Concerning the `severity_type_323dfc7` error, here's what I observed:
> 
> In this [Case Sync Request run log](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06352646-2041-73d7-a543-e9ef1b8a9483) (cid `1439200005793` ), the `severity_type_323dfc7` is an array:
> 
> ```
> "riskLevel": "high",
>         "severityType": [
>             "ทางเพศ",
>             "ทางจิตใจ"
>         ],
>         "sex": "หญิง",
> ```
> 
> However, in the [job script](https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js#L2911-L2918) I'm not sure if the data is being sent as an array into Primero

@jayesse i have pushed a fix for this issue #78

**Comment by jayesse** [comment]
@mtuchi I re-run all the failed jobs from this morning, and I got a new error for cid  1417300016213

```
 "errors": [
      {
        "status": 422,
        "resource": "/api/v2/cases/447b7d35-fab1-4542-9c42-013414768a14",
        "detail": [
          "/plh_caregiver_first_name_93f7d52",
          "/plh_caregiver_last_name_1215238",
          "/plh_caregiver_address_39fa009",
          "/plh_caregiver_contact_c216042"
        ],
        "message": "Invalid Record JSON"
      }
```

Failed sync - https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06352903-1b5e-73c9-9918-46115c7c7d17
Parent run - https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/063528f6-ff72-7908-a08e-fe61ada4a5a0

CC @aleksa-krolls

**Comment by mtuchi** [comment]
> @mtuchi I re-run all the failed jobs from this morning, and I got a new error for cid 1417300016213
> 
> ```
>  "errors": [
>       {
>         "status": 422,
>         "resource": "/api/v2/cases/447b7d35-fab1-4542-9c42-013414768a14",
>         "detail": [
>           "/plh_caregiver_first_name_93f7d52",
>           "/plh_caregiver_last_name_1215238",
>           "/plh_caregiver_address_39fa009",
>           "/plh_caregiver_contact_c216042"
>         ],
>         "message": "Invalid Record JSON"
>       }
> ```
> 
> Failed sync - https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06352903-1b5e-73c9-9918-46115c7c7d17 Parent run - https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/063528f6-ff72-7908-a08e-fe61ada4a5a0
> 
> CC @aleksa-krolls

In mapping spec, we are seeing the "answersList" as a "string" but in this run log 
https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/063528f6-ff72-7908-a08e-fe61ada4a5a0
(Line 288) The "answersList" is an array 

The same goes for 
```
/plh_caregiver_last_name_1215238",
"/plh_caregiver_address_39fa009",
"/plh_caregiver_contact_c216042"
```

Has there been a change in child shield? and how should we handle this?
cc @jayesse @aleksa-krolls

**Comment by jayesse** [comment]
@aleksa-krolls I propose we close this issue as the current error `Invalid Record JSON` is different from the original problem (`severity_type_323dfc7`).

We can open a new issue once we get feedback from the client.
