### ISSUE TITLE
Flow1-Job3: Filter `physical_check_2` assessments to exclude records where source = `HIS`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#82]
## Background, context, and business value
See issue #47 for the original issue spec. This job maps the data we got from Primero in J1 and applies the translations we got in J2 before syncing to Child Shield. **[See data flow diagram](https://lucid.app/lucidchart/b8ee8b9d-2f0f-4d19-b12e-908d4138ccb4/edit?viewport_loc=2627%2C350%2C2274%2C1123%2Cgz2GymXUIyeW&invitationId=inv_093b1b38-48bc-421c-a25e-0fbb5a1b7a8d).** 

The client says we are currently sending "HIS" information to Child Shield in the Job3 step, but they would only like to send "Primero" information. See new step in orange box: 
<img width="428" alt="Screen Shot 2022-11-02 at 8 33 36 PM" src="https://user-images.githubusercontent.com/16758106/199575103-0b97a3c8-830b-423d-8687-589b6a80f952.png">

## The specific request, in as few words as possible
Where we map the array of `physical_check_2` forms, please add a filter to EXCLUDE items from this array if `pc2.source_of_information_44cac9a === 'his'
https://github.com/OpenFn/primero-thailand/blob/c3a5f815976bc383cefb7e845adc0765bb86f22f/jobs/child-shield/syncInterventionsToChildShield.js#L897-L900

Use the sample state below to see data where `his` pc2 forms are currently being mapped to Child Shield - or see [L387 in this run log(https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0635630f-7200-7e66-98df-4fdc663dd750). 

## state.json

JOB 1 - Update the manual cursor to `2022-10-23T00:00:00.177Z`; you should see at least cases with case_id_display `164e909` returned like [in this run](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0635630e-90d3-755f-8063-4d8a28bdbfd0). 
```
{
  "configuration": { "SEE LP Primero Thailand Demo API User (Open Function)" },
  "cursor": "Fetch cases where "last_updated_at" >= '2022-10-23T00:00:00.177Z"
}
```
JOB 2:
```
{
  "configuration": ["See LP MOPH Thailand HIS API - DEMO Alpha (Unicef)'"],
  "data": { "data generated by GET job"},
}
```
JOB 3:
```
{
  "configuration": ["See LP MOPH Thailand HIS API - DEMO Alpha (Unicef)'"],
  "data": { "final state of last 2 jobs"},
}
```

## adaptor
J1 & J1 - `primero`
J3 - `http`

### API Docs
[Child Shield API docs](https://docs.google.com/document/d/1GIRxVXSZLgmKwTf-dP0kQjto5-VdZl5GjCj-pAjKfaA/edit#heading=h.54fpob4z8r60)
[Child Shield Sample Postman Requests](https://docs.google.com/document/d/1GIRxVXSZLgmKwTf-dP0kQjto5-VdZl5GjCj-pAjKfaA/edit#)
[Primero API docs](https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api)

## trigger
Job 1: Cron
Job 2: Flow
Job 3: Flow

## expression.js
Update the job *on the `staging` branch*
https://github.com/OpenFn/primero-thailand/blob/staging/jobs/child-shield/syncInterventionsToChildShield.js#L897-L900

## Toggl
UNICEF Thailand

**Comment by aleksa-krolls** [comment]
@mtuchi to pick up tomorrow please, holler with questions!
cc @jayesse

**Comment by aleksa-krolls** [comment]
@mtuchi When you try to replicate this locally...heads up I was trying to run Job1 with this cursor to test something related... and I don't understand why the get Job1 is not returning case with `"short_id": "164e909"`. 

If I go and get this case `164e909` - [see here](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06362ca7-6f3d-7576-bf28-378be3fad411) for the API response. 
`"last_updated_at": "2022-11-02T19:45:27.998Z"`

^This date is later than the manual cursor I set when I ran Job1 ([see run log](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06362ca9-ed0e-75e2-8086-ec96e5ef5082)). So do you have any idea _why_ this case `164e909` does _not_ appear in the output of the getCases() step?

**Comment by mtuchi** [comment]
@aleksa-krolls i have filtered `physical_check_2` to return an empty array `[]` if `pc2.source_of_information_44cac9a === 'his'` 

I have merged change #84 so that you can test it on `platform app`, Let me know if that is the desired output or if we only need to change `source_of_information_44cac9a` field.

**Comment by aleksa-krolls** [comment]
@mtuchi We don't want to return `[ ]` if _any_ of the pc2 items have `his`. Rather, we want to exclude only those where source = `his`, but keep the rest so that we can still map `primero` assessments. I therefore propose using `.filter(...)` rather than `.find(..)`. 

[See my commit](https://github.com/OpenFn/primero-thailand/commit/f45468742a163a0f2d3cdf0f2978f2cb249c14a2) with proposed change like this: 
```
physical_check_2: cs.physical_check_2
? cs.physical_check_2
    .filter(pc2 => pc2.source_of_information_44cac9a !== 'his')
    .map(pc2 => ({
      ...all the field mappings
    }))
    .flat()
: [],
```
I'm testing now on platform to validate, but please feel free to provide feedback/make edits to how I implemented this to meet your coding best practices. Just want to make sure given an input like this...
```
physical_check_2: [ {item: 1, source: his}, {item: 2, source: primero, selectField: blah,}]
```
the output should look like this (where the `his` item is discarded)...
```
physical_check_2: [ {item: 2, source: primero, selectField: blahTranslated}]
```

**Comment by aleksa-krolls** [comment]
@mtuchi this is working! [See run log](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06363e70-40ac-7d2d-91a6-77ec21462c2e). If you want to edit my code further, feel free to move back to backlog. Otherwise let's close this issue.

**Comment by mtuchi** [comment]
> physical_check_2

@aleksa-krolls this looks good and i solves the problem so we can close the issue now 👍🏽

**Comment by jayesse** [comment]
Hi @aleksa-krolls and @mtuchi I'm closing this issue now. Thanks
