### ISSUE TITLE
Flow1-Job3: translation mapping errors with 2 fields

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#85]
## Background, context, and business value
See issue #47 for the original issue spec. This job maps the data we got from Primero in J1 and applies the translations we got in J2 before syncing to Child Shield. **[See data flow diagram](https://lucid.app/lucidchart/b8ee8b9d-2f0f-4d19-b12e-908d4138ccb4/edit?viewport_loc=2627%2C350%2C2274%2C1123%2Cgz2GymXUIyeW&invitationId=inv_093b1b38-48bc-421c-a25e-0fbb5a1b7a8d).** 

See this run log for a recently successful run. I have some questions about a couple fields in this output. 
https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06363e70-40ac-7d2d-91a6-77ec21462c2e

### 1. `service_type` mapping missing translation? 
See L279 in the run log. It looks like that the Thai translated label outputted for the selected `service_type` option is in English. 
Instead of `IQ Test`, I'd expect to see the Thai translation of `livelihoods_service`. Is this an issue in our job? Or do they not have the correct Thai translations uploaded in Primero for `service_type`? 
```
"services_section": [
        {
          "unique_id": "e2c85bac-8af8-4d84-b75e-7c8d1378b59f",
          "service_type": {
            "livelihoods_service": "IQ Test"
          },
```

### 2. `service_response_timeframe` mapping throws TypeError
When I add this mapping into the job, it throws this error and [the run fails - see log](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06363e40-ea90-7397-8df9-6368b8bd9858): `TypeError [Error]: Cannot read properties of undefined (reading '3_hours')`. If I comment out the mapping, the job runs successfully. What's wrong with this specific mapping?
https://github.com/OpenFn/primero-thailand/blob/25d0198c7d75d8f6804e173550cf63c6b268a883/jobs/child-shield/syncInterventionsToChildShield.js#L745-L752

## state.json

JOB 1 - Run the job with the manual cursor`2022-11-02T00:25:04.177Z`; you should see at least cases with case_id_display `164e909` returned like [in this run](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06363e3f-8780-792b-bc27-8b814fa7ed7a). 
```
{
  "configuration": { "SEE LP Primero Thailand Demo API User (Open Function)" },
  "cursor": "Fetch cases where "last_updated_at" >= '2022-11-02T00:25:04.177Z"
}
```
JOB 2:
```
{
  "configuration": ["See LP MOPH Thailand HIS API - DEMO Alpha (Unicef)'"],
  "data": { "data generated by GET job"},
}
```
JOB 3:
```
{
  "configuration": ["See LP MOPH Thailand HIS API - DEMO Alpha (Unicef)'"],
  "data": { "final state of last 2 jobs"},
}
```

## adaptor
J1 & J1 - `primero`
J3 - `http`

### API Docs
[Child Shield API docs](https://docs.google.com/document/d/1GIRxVXSZLgmKwTf-dP0kQjto5-VdZl5GjCj-pAjKfaA/edit#heading=h.54fpob4z8r60)
[Child Shield Sample Postman Requests](https://docs.google.com/document/d/1GIRxVXSZLgmKwTf-dP0kQjto5-VdZl5GjCj-pAjKfaA/edit#)
[Primero API docs](https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api)

## trigger
Job 1: Cron
Job 2: Flow
Job 3: Flow

## expression.js
Update the job *on the `staging` branch*
https://github.com/OpenFn/primero-thailand/blob/staging/jobs/child-shield/syncInterventionsToChildShield.js#L724-L787

## Toggl
UNICEF Thailand

**Comment by aleksa-krolls** [comment]
@mtuchi can you please pick this up tomorrow? Holler with questions!

**Comment by mtuchi** [comment]
> @mtuchi can you please pick this up tomorrow? Holler with questions!

@aleksa-krolls i have fixed and merge changes for `service_response_timeframe` mapping throws TypeError on #86 
Please test on platform-app 

For `service_type` mapping missing translation?
This 👇🏽 is the result of `getLookup` which is used to fetch translations, As you can see both `th` values are in English, 
```
 {
"id": "legal_assistance_service",
"disabled": false,
"display_text": {
    "ar": "",
    "en": "Psychological test",
    "fr": "",
    "th": "Psychological test"
}
},
{
"id": "livelihoods_service",
"disabled": false,
"display_text": {
    "ar": "",
    "en": "IQ test",
    "fr": "",
    "th": "IQ Test"
}
},
```
That's why we are seeing this 👇🏽 
```
 "service_type": {
            "livelihoods_service": "IQ Test"
          },
```

**Comment by aleksa-krolls** [comment]
Client said this is OK and how the data is setup - fine to leave as is
