### ISSUE TITLE
Flow2-Job1: TypeError [Error]: Cannot set properties of null (setting 'password')

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-thailand#89]
## Describe the bug
See run failure with this error: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06368788-b4c6-7f78-841f-31a1be120a46

## To Reproduce
Feel free to retry [this run](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06368788-b4c6-7f78-841f-31a1be120a46) against this Message to reproduce the error: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/06368788-aacc-709e-84ad-2917504ff5dd

### expression.js
**Please make all changes against the `staging` branch:** 
https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1-getPatientData.js

`language-http@4.0.0`

### state.json

Either provide state directly, or link to a file. If sensitive information
should be in state, redact it and provide instructions for where it can be
found.

```json
{
  "configuration": ["SEE LP: 'MOPH Thailand HIS API - DEMO Alpha (Unicef)'"],
  "data": {Use this Message: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/06368788-aacc-709e-84ad-2917504ff5dd},
}
```

## Expected behavior
The job should either successfully find the patient or not, depending on the HIS API response.

## To test/resolve
Feel free to re-test against the Message linked to above

## Toggl 
UNICEF Thailand

**Comment by aleksa-krolls** [comment]
hey @mtuchi - this is a new one. Can you please check it out today?

**Comment by jayesse** [comment]
@mtuchi Closing this issue as there are ongoing problems with the Thailand Primero demo server.

**Comment by aleksa-krolls** [comment]
@jayesse @mtuchi the servers are back up, but I'm still seeing this error. See recent run failure below: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0636b4c3-a03c-7045-b098-f17cdb0eaeb2

Mtuchi, can you please check this out? Thanks!

**Comment by mtuchi** [comment]
> @jayesse @mtuchi the servers are back up, but I'm still seeing this error. See recent run failure below: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0636b4c3-a03c-7045-b098-f17cdb0eaeb2
> 
> Mtuchi, can you please check this out? Thanks!

@aleksa-krolls I have improved error logging, when `GET` request for `/people/findOne` fails. on #90, You can test on platform to see a `safeError` logs 
cc @jayesse

**Comment by aleksa-krolls** [comment]
Looking good, thanks @mtuchi
