### ISSUE TITLE
Set empty strings and empty arrays to null before upserting Primero

### ISSUE THREAD

**Issue by jayesse** [OpenFn/unicef-thailand#92]
## Background, context, and business value

Improve the `Flow 2 - 2`  upsert job to set all field values in Primero to  null, whenever an empty string ("") or empty array [] is received from Child Shield. This change applies to all fields in this [mapping document](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=1877091315)

## The specific request, in as few words as possible
In this [example run](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0637c24b-5c4d-74d0-9f02-ee0bf87e533a), an empty array was received from Child Shield for the following fields:

```
plh_caregiver_first_name_93f7d52,
plh_caregiver_last_name_1215238,
plh_caregiver_address_39fa009,
plh_caregiver_contact_c216042
```

The request is to update the [upsert job](https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js) so that when an empty array or string is received from Child Shield, it should set the value to `null` and then upsert Primero

### expression.js
*Please make changes in the `staging` branch!* ⚠️
Link to the job itself in Github: https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js

#### adaptor
`language-primero@2.9.1`

### state.json
This is step 2 job in a flow. 
1. Run job1 `/staging/jobs/1-getPatientData.js` to generate state for job 2. 
- state.configuration: `MOPH Thailand HIS API - DEMO Alpha (Unicef)`
- state.data: Use the GET request output from this job run: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06383fa3-7d36-768c-96c6-b26f02b25c9d.
The `record_id` can be retrieved here: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/06383fa3-7322-7577-8efc-065ac2ef5048
2.  Use the final state of the first job to run the 2nd job
- `state.configuration`: see LP `Primero Thailand Demo API User (Open Function)` (Note... this user is for **basic auth**.)

## output.json
There should be no fields with empty strings or empty arrays in the job logs.  Verify this by re-running the Flow 2-1 job with [this message](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/0637c24a-ec8e-7fe6-95a3-04c970b9758c), which will then trigger a re-run of the Flow 2-2 job. Afterwards, check the value of the following fields:

```
plh_caregiver_first_name_93f7d52,
plh_caregiver_last_name_1215238,
plh_caregiver_address_39fa009,
plh_caregiver_contact_c216042
```

## Toggl 

UNICEF Thailand

**Comment by mtuchi** [comment]
@aleksa-krolls I have fixed this issue on https://github.com/OpenFn/primero-thailand/commit/9bb4c235c0c00eab3c9b8d150d81294e1cf45d1b, Please try to test on platform-app 
cc @jayesse

**Comment by jayesse** [comment]
@mtuchi Your latest update fixed the issue, as evident from [this log](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/063861d8-5485-7e72-83bf-a87c234e7c3b). Thus I'm closing the issue. Thanks for your assistance.
