### ISSUE TITLE
Flow2-Job2 error: Cannot read properties of undefined (reading 'answersList')

### ISSUE THREAD

**Issue by jayesse** [OpenFn/unicef-thailand#94]
## Describe the bug
A primero user clicked the `Sync` button in Primero that triggered this Flow 2-1 [job run](https://openfn.org/projects/primero-thailand-io-unicef---staging/runs/063a1868-b7bc-7d85-9b7d-21b229386db4) to OpenFn with these case details: 
`"national_id_no": "1399900518123"`
`Record ID:  6052c6f9962a71ec9c710f29`

However, when this [Flow 2-2 sync job](https://openfn.org/projects/primero-thailand-io-unicef---staging/jobs/jyzqmq/) is triggered, the following error is found in the [Flow 2-2 run log](https://openfn.org/projects/primero-thailand-io-unicef---staging/runs/063a1869-4313-716c-a78d-7989a0b501a4) , and hence the sync fails.

```
TypeError [Error]: Cannot read properties of undefined (reading 'answersList')
    at vm.js:2909:38
    at Array.map (<anonymous>)
    at magicallyBuildMapping (vm.js:2881:12)
    at vm.js:3389:28
    at VM2 Wrapper.apply (/home/app/assets/node_modules/vm2/lib/bridge.js:485:11)
    at Array.forEach (<anonymous>)
    at VM2 Wrapper.apply (/home/app/assets/node_modules/vm2/lib/bridge.js:485:11)
    at vm.js:3375:29
    at VM2 Wrapper.apply (/home/app/assets/node_modules/vm2/lib/bridge.js:485:11)
    at /home/app/priv/language_packs/language-primero-v2.9.1/node_modules/@openfn/language-common/lib/Adaptor.js:101:12

```

## To Reproduce
1. Run job 1 `/staging/jobs/1-getPatientData.js` with this Message as state.data: https://github.com/OpenFn/primero-thailand/blob/staging/sampleData/cid_1399900518123_sync_request.json
4. Then run job 2 `staging/jobs/1b-upsertCases.js` with the final state from this Job 1 run or use this state.json directly: https://github.com/OpenFn/primero-thailand/blob/staging/sampleData/cid_1399900518123_flow2_state.json 

The run will look like this: https://openfn.org/projects/primero-thailand-io-unicef---staging/runs/063a1869-4313-716c-a78d-7989a0b501a4

We want to troubleshoot the errors found.

### expression.js
*Please make changes in the `staging` branch!* ⚠️
Link to the job itself in Github: https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js

#### adaptor
`language-primero@2.9.1`

### state.json
This is step 2 job in a flow. 
1. Run job1 `/staging/jobs/1-getPatientData.js` to generate state for job 2. 
- state.configuration: `MOPH Thailand HIS API - DEMO Alpha (Unicef)`
- state.data: Use this Message: https://github.com/OpenFn/primero-thailand/blob/staging/sampleData/cid_1399900518123_sync_request.json
2.  Use the final state of the first job to run the 2nd job or use this json directly: https://github.com/OpenFn/primero-thailand/blob/staging/sampleData/cid_1399900518123_flow2_state.json

- `state.configuration`: see LP `Primero Thailand Demo API User (Open Function)` (Note... this user is for **basic auth**.)

## Expected behavior
We should see the correct data loaded to Primero. instead of th errors shown 

## To test/resolve
1. After the desired output is working locally, please push commits to `staging`.
2. I will then re-run [this job run](https://openfn.org/projects/primero-thailand-io-unicef---staging/runs/063a1869-4313-716c-a78d-7989a0b501a4) to re-trigger the flow on platform. 
3. If the problem is resolved, then this other cid `1419902839236` which experiences this same problem should sync correctly to Primero

## Toggl 
UNICEF Thailand

**Comment by aleksa-krolls** [comment]
@mtuchi is this in progress?

**Comment by mtuchi** [comment]
> @mtuchi is this in progress?

@aleksa-krolls this is fixed, you can now test on platform-app, cc @jayesse

**Comment by jayesse** [comment]
@mtuchi I have tested for the two reported cids `1399900518123` and `1419902839236` and the job now runs successfully. Can you please confirm that the failure was due to the array `answersList` being missing for certain questions?

If so, can we add some log of such questions, so that the client would know where to make changes and subsequently sync all relevant data from Child Shield?

**Comment by mtuchi** [comment]
> @mtuchi I have tested for the two reported cids `1399900518123` and `1419902839236` and the job now runs successfully. Can you please confirm that the failure was due to the array `answersList` being missing for certain questions?
> 
> If so, can we add some log of such questions, so that the client would know where to make changes and subsequently sync all relevant data from Child Shield?

@jayesse I have added logs to help troubleshoot the missing data for questions, See the logs -> https://openfn.org/projects/primero-thailand-io-unicef---staging/runs/063a2b31-00df-73ea-aca6-e152bc51aeb2

**Comment by jayesse** [comment]
Closing this issue as the problem has been fixed. Many thanks
