### ISSUE TITLE
PSU participant details not synced with Primero

### ISSUE THREAD

**Issue by jayesse** [OpenFn/unicef-thailand#95]
## Background, context, and business value

Some fields from Child Shield, specifically the PSU participant details, are not being synced with Primero. Instead, they are being set to `null`, instead of their actual values received in the Child Shield API response.

Refer to rows 51 - 55 in this [mapping document](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=1877091315)

## The specific request, in as few words as possible
In lines 230 - 253 of this [sample run](https://openfn.org/projects/primero-thailand-io-unicef---staging/runs/063b6994-a648-75d7-8b02-7b8ca352fd36) of the Primero sync request, there are values present in the `answersList` variables. However, when the [Flow 2-2 Upsert cases in Primero Job](https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js) runs , the following fields return `null` values to Primero:

```
"plh_caregiver_first_name_93f7d52": null,
"plh_caregiver_last_name_1215238": null,
"plh_caregiver_address_39fa009": null,
"plh_caregiver_contact_c216042": null,
"age_60ee953": null,
```

**[Here](https://openfn.org/projects/primero-thailand-io-unicef---staging/runs/063bd572-2219-7731-90a7-55ba7f7ccae7)** is a sample Flow 2-2 run showing null values for these fields.

The request is to troubleshoot the [upsert job](https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js) so that the PSU participant details received from Child Shield are properly upsert to Primero

### expression.js
*Please make changes in the `staging` branch!* ⚠️
Link to the job itself in Github: https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js

#### adaptor
`language-primero@2.9.1`

### state.json
This is step 2 job in a flow. 
1. Run job1 `/staging/jobs/1-getPatientData.js` to generate state for job 2. 
- state.configuration: `MOPH Thailand HIS API - DEMO Alpha (Unicef)`
- state.data: Use the GET request output from this job run: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06383fa3-7d36-768c-96c6-b26f02b25c9d.
The `record_id` can be retrieved here: https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/06383fa3-7322-7577-8efc-065ac2ef5048
2.  Use the final state of the first job to run the 2nd job
- `state.configuration`: see LP `Primero Thailand Demo API User (Open Function)` (Note... this user is for **basic auth**.)

## output.json
There should be no fields with null values in the job logs where Child Shield has sent the right values.  Verify this by re-running the Flow 2-1 job with [this message](https://openfn.org/projects/primero-thailand-io-unicef---staging/messages/063b6994-9bc9-77b0-9797-2a4300a0758c), which will then trigger a re-run of the Flow 2-2 job. Afterwards, check the value of the following fields:

```
plh_caregiver_first_name_93f7d52
plh_caregiver_last_name_1215238
plh_caregiver_address_39fa009
plh_caregiver_contact_c216042
age_60ee953
```

## Toggl 

UNICEF Thailand

**Comment by mtuchi** [comment]
@jayesse 
I have fixed the values for the following fields
```
plh_caregiver_first_name_93f7d52
plh_caregiver_last_name_1215238
plh_caregiver_address_39fa009
plh_caregiver_contact_c216042
```

For `age_60ee953` i have noticed `groupDescription` have changed from `ข้อมูลเพื่อติดต่อผู้เข้าร่วมโครงการ` to `ส่วนที่ 1 รายละเอียดเกี่ยวกับภูมิหลังของคุณ (14 ข้อ)` This is causing the value to be `null` 

Can you double-check if we need to update the `groupDescription` mapping for question `1. คุณมีอายุเท่าใด` which correspond to `age_60ee953`

**Comment by mtuchi** [comment]
@jayesse i have fixed the mapping for the remaining PSU fields -> be44448f8df8f8d467520042add63661327da2fb, you can test on platform-app

**Comment by jayesse** [comment]
@mtuchi My tests are successful. I have written to the customer to verify. We can close this issue now. Thanks for your help!
