### ISSUE TITLE
Modify Assessment date fields to map to either CQ1 or CQ2 dates

### ISSUE THREAD

**Issue by jayesse** [OpenFn/unicef-thailand#96]
## Background, context, and business value

Update the `Flow 2 - 2`  upsert job by updating the logic of the assessment date fields below:

`assessment_date_a745d8b` (week 1) 
`assessment_date_5f07c55` (week14)

## The specific request, in as few words as possible
 The Child Quality of Life (CQ) fields have two assessment dates: One for week 1, the other for Week 14. It turns out that:
- If the child is between 2 - 6 years, only CQ1 fields are populated by child shield.
- If the child is between 7 - 9 years, only CQ2 fields are populated by child shield.

At the moment, the [Flow 2-2 upsert job](https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js) scans the Child shield response for the objects containing **question code CQ1** (`"questionnaire_code": "CQ1"`) and then fetches the two “date” values and then compares the two. The earlier date is then assigned to CQ1 week 1, while the later date is assigned as CQ1 week 14. 

We need to actually improve this logic by checking for an object containing question code CQ1 (`"questionnaire_code": "CQ1"`) first, and if it is not present, we check for an object containing question code AUQUEI_CQ2 (`"questionnaire_code": "AUQUEI_CQ2"`) and then use the two dates in that object to populate the assessment date fields

The assessment fields dates are:
`assessment_date_a745d8b` (week 1) 
`assessment_date_5f07c55` (week14)

Note: The client has confirmed that we should encounter a situation **in production** where _both_ CQ1 and AUQUEI_CQ2 question codes are present.

### expression.js
*Please make changes in the `staging` branch!* ⚠️
Link to the job itself in Github: https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js

#### adaptor
`language-http@4.0.0`

### state.json
This is step 2 job in a flow. 
1. Run job1 `/staging/jobs/1-getPatientData.js` to generate state for job 2. 
- state.configuration: `MOPH Thailand HIS API - DEMO Alpha (Unicef)`
- state.data: Use this Message: https://openfn.org/projects/primero-thailand-io-unicef---staging/runs/06361e9e-8831-748d-95f4-2cc588d3cf3a
2.  Use the final state of the first job to run the 2nd job
- `state.configuration`: see LP `Primero Thailand Demo API User (Open Function)` (Note... this user is for **basic auth**.)

## output.json
The job should populate the Child Quality of Life (CQ) assessment dates with either CQ1 dates or AUQUEI_CQ2 dates, depending on which one is present.

Hence, for CIDs 1418800048611, which has only AUQUEI_CQ2 data, we expect to see the assessment dates populated for Week 1 and Week 14. We will verify this by re-running the [Flow 2-1 job](https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1-getPatientData.js) with [this message](https://openfn.org/projects/primero-thailand-io-unicef---staging/messages/063c90f8-277f-7e4d-9876-68bb06964ed0), which will then trigger a re-run of the Flow 2-2 job. Afterwards, check the Flow 2-2 logs for the following fields:

`assessment_date_a745d8b` (week 1) 
`assessment_date_5f07c55` (week14)

## Toggl 

UNICEF Thailand

**Comment by mtuchi** [comment]
> ## Background, context, and business value
> Update the `Flow 2 - 2` upsert job by updating the logic of the assessment date fields below:
> 
> `assessment_date_a745d8b` (week 1) `assessment_date_5f07c55` (week14)
> 
> ## The specific request, in as few words as possible
> The Child Quality of Life (CQ) fields have two assessment dates: One for week 1, the other for Week 14. It turns out that:
> 
> * If the child is between 2 - 6 years, only CQ1 fields are populated by child shield.
> * If the child is between 7 - 9 years, only CQ2 fields are populated by child shield.
> 
> At the moment, the [Flow 2-2 upsert job](https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js) scans the Child shield response for the objects containing **question code CQ1** (`"questionnaire_code": "CQ1"`) and then fetches the two “date” values and then compares the two. The earlier date is then assigned to CQ1 week 1, while the later date is assigned as CQ1 week 14.
> 
> We need to actually improve this logic by checking for an object containing question code CQ1 (`"questionnaire_code": "CQ1"`) first, and if it is not present, we check for an object containing question code AUQUEI_CQ2 (`"questionnaire_code": "AUQUEI_CQ2"`) and then use the two dates in that object to populate the assessment date fields
> 
> The assessment fields dates are: `assessment_date_a745d8b` (week 1) `assessment_date_5f07c55` (week14)
> 
> Note: The client has confirmed that we should encounter a situation **in production** where _both_ CQ1 and AUQUEI_CQ2 question codes are present.
> 
> ### expression.js
> _Please make changes in the `staging` branch!_ warning Link to the job itself in Github: https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js
> 
> #### adaptor
> `language-http@4.0.0`
> 
> ### state.json
> This is step 2 job in a flow.
> 
> 1. Run job1 `/staging/jobs/1-getPatientData.js` to generate state for job 2.
> 
> * state.configuration: `MOPH Thailand HIS API - DEMO Alpha (Unicef)`
> * state.data: Use this Message: https://openfn.org/projects/primero-thailand-io-unicef---staging/runs/06361e9e-8831-748d-95f4-2cc588d3cf3a
> 
> 2. Use the final state of the first job to run the 2nd job
> 
> * `state.configuration`: see LP `Primero Thailand Demo API User (Open Function)` (Note... this user is for **basic auth**.)
> 
> ## output.json
> The job should populate the Child Quality of Life (CQ) assessment dates with either CQ1 dates or AUQUEI_CQ2 dates, depending on which one is present.
> 
> Hence, for CIDs 1418800048611, which has only AUQUEI_CQ2 data, we expect to see the assessment dates populated for Week 1 and Week 14. We will verify this by re-running the [Flow 2-1 job](https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1-getPatientData.js) with [this message](https://openfn.org/projects/primero-thailand-io-unicef---staging/messages/063c90f8-277f-7e4d-9876-68bb06964ed0), which will then trigger a re-run of the Flow 2-2 job. Afterwards, check the Flow 2-2 logs for the following fields:
> 
> `assessment_date_a745d8b` (week 1) `assessment_date_5f07c55` (week14)
> 
> ## Toggl
> UNICEF Thailand

@jayesse i have fixed this on d4b04bb9dc20f5bbc90abb197f67fd6558ce073f please double check on platform-app

**Comment by jayesse** [comment]
@mtuchi This issue is resolved. Thanks for your assistance. Closing this now
