### ISSUE TITLE
Add separate logic to Upsert Job to handle CQ2 questions

### ISSUE THREAD

**Issue by jayesse** [OpenFn/unicef-thailand#97]
## Background, context, and business value

Update the `Flow 2 - 2`  upsert job by adding separate logic  to handle the CQ2 questions for Children aged 7 - 9.

## The specific request, in as few words as possible
 The current job looks out for either CQ1 or CQ2 data from Child Shield in order to determine the assessment dates. The ask here is to extend this check such that

1. When Child Shield sends **CQ1** data, we the main Primero questions `1,2,3,4,5,6,7 and 8` would be populated for the Child Quality of Life Section
2. When Child Shield sends **CQ2** data, we the main Primero questions `1,2,3,4,6,7 and 8` (notice no.5 is omitted), as well as  additional questions `1 - 11` would be populated for the Child Quality of Life Section.

Follow this [**mappings specs**](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=1877091315) for CQ1 (Rows 6 - 14) and CQ2 (Rows 16 - 37) to add the relevant logic to the [Flow 2-2 upsert job](https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js).

As a guide, CQ values in Child Shield API Response can be fetched as follows:
For **CQ1**, We search for the object containing `"questionnaire_code": "CQ1"` and use the format above to locate and populate the CQ1 fields
For **CQ2,** We search for the object containing `"questionnaire_code": "AUQUEI_CQ2"` and use the format above to locate and populate the main CQ2 fields.

We then use:
 `"groupDescription": "ส่วนที่ 2: แบบสอบถามคุณภาพชีวิตฉบับเพิ่มเติม (CQ2) จำนวน 7 ข้อ"` to locate and populate the main questions 1, 2,3,4, 6, 7, 8.
`"groupDescription": "ส่วนที่ 1: แบบสอบถามคุณภาพชีวิต (AUQUEI) จำนวน 11 ข้อ"` to locate and populate the additional questions 1- 11

Finally, we compare the `date` fields in these objects to determine Week 1 and Week 14 values 

### expression.js
*Please make changes in the `staging` branch!* ⚠️
Link to the job itself in Github: https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js

#### adaptor
`language-http@4.0.0`

### state.json
This is step 2 job in a flow. 
1. Run job1 `/staging/jobs/1-getPatientData.js` to generate state for job 2. 
- state.configuration: `MOPH Thailand HIS API - DEMO Alpha (Unicef)`
- state.data: Use this Message: https://openfn.org/projects/primero-thailand-io-unicef---staging/runs/06361e9e-8831-748d-95f4-2cc588d3cf3a
3.  Use the final state of the first job to run the 2nd job
- `state.configuration`: see LP `Primero Thailand Demo API User (Open Function)` (Note... this user is for **basic auth**.)

## output.json
The job should populate the Child Quality of Life (CQ) based on whether CQ1 data or AUQUEI_CQ2 data is present.

For example, for CIDs 1418800048611, which has only AUQUEI_CQ2 data, we expect to see CQ main questions 1,2,3,4,6,7,8 and additional questions 1 - 11  populated, for both Week 1 and Week 14. We will verify this by re-running the [Flow 2-1 job](https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1-getPatientData.js) with [this message](https://openfn.org/projects/primero-thailand-io-unicef---staging/messages/063c90f8-277f-7e4d-9876-68bb06964ed0), which will then trigger a re-run of the Flow 2-2 job. Afterwards, check the Flow 2-2 logs for the following fields:

## Toggl 

UNICEF Thailand

**Comment by mtuchi** [comment]
@jayesse I have made good progress on updating the mapping logic for CQ2 on this push 2afa69f, please QA this on platform-app. Also, I have noticed that if we only have data for CQ1 then questions 1- 11 with `"groupDescription": "ส่วนที่ 1: แบบสอบถามคุณภาพชีวิต (AUQUEI) จำนวน 11 ข้อ"` will have `null` after mapping, Is this the desired result for such scenario? 

##### Expected output if we only CQ1 data for question 1-11 with `"groupDescription": "ส่วนที่ 1: แบบสอบถามคุณภาพชีวิต (AUQUEI) จำนวน 11 ข้อ"`
```
"how_do_you_feel_when_you_think_of__name_of_primary_caregiver_in_plh_programme___c5c225b": null,
"how_do_you_feel_when_you_play_with_name_of_primary_caregiver_in_plh_programme___5e1d546": null,
"how_do_you_feel_when__name_of_primary_caregiver_in_plh_programme__mentions_you__f8e280b": null,
"how_do_you_feel_when___name_of_primary_caregiver_in_plh_programme__tells_you_what_to_do__227f1d5": null,
```

**Comment by jayesse** [comment]
@mtuchi I tested successfully. The client has also tested successfully. Closing the issue now, as we're going live this weekend. Thanks for your support!!
